language: node_js
node_js:
#  - "0.8"
  - "0.10"
  - "0.12"
  - "4.2"
  - "4.4"
  - "5"
  - "6"
  - "7"
  - "8"

before_install:
  - "if [[ `node -v` == v0.8.* ]]; then npm install -g npm || exit 0; fi"

script:
  - npm run lint
  - npm run coverage
  - npm run buildertest
  - npm run browsertest
  - npm run react-native-test
  - node ./node_modules/.bin/codecov

sudo: false
